Added back function to incorporate a self-signed or otherwise bad cert
mend-toolkit/mend-examples pull request #122
Opened 2023-08-01 15:01 UTC by hugh-mend

2023-08-04 19:03 UTC, hugh-mend commented
Hi @samq-ws this self-signed-cert code got lost in the refactoring.  Also the code was broken due to some changes in how the images were built; I think I've fixed that.

2023-08-04 20:16 UTC, randygeyer-ws commented
There's a better way to incorporate certs into the containers that requires no DockerFile changes.  I don't support this method.

2023-08-04 20:18 UTC, randygeyer-ws commented on Repo-Integration/Self-Hosted/setup.sh
> +function cert_add(){
There's a better way to incorporate certs into the containers that require no changes to the dockerfiles.  I don't support this approach.

2023-08-04 20:19 UTC, randygeyer-ws reviewed
There's a better way to incorporate certs into the containers that require no changes to the dockerfiles. I don't support this approach.

2023-08-04 20:25 UTC, samq-ws requested changes
@hugh-mend , please meet with @randygeyer-ws offline and find a way to document his better approach for customers.

2023-09-01 14:48 UTC, samq-ws commented
Please see [this addition](https://github.com/mend-toolkit/mend-examples/blob/main/Repo-Integration/Self-Managed/certs.md)

2023-09-01 14:48 UTC, closed without merging