Creates a script to get the age for each direct dependency
mend-toolkit/mend-examples pull request #168
Opened 2023-12-27 20:32 UTC by kyallanum-MND

2023-12-27 22:36 UTC, samq-ws requested changes
Errored out with
./get-library-age.sh: line 112: 1703716452 - : syntax error: operand expected (error token is "- ")

2023-12-27 22:36 UTC, samq-ws commented on Scripts/Mend SCA/get-library-age.sh
> +	echo $LOGIN_RESPONSE
These echos seems like leftover debug code

2023-12-27 23:48 UTC, kyallanum-MND commented
Going to delete this script as it does not seem to work at the scale needed and develop in Python.

2023-12-29 22:01 UTC, samq-ws requested changes
Due to scale being an issue with this script.  I would add an option to run for a specific product.

2024-01-03 22:24 UTC, samq-ws requested changes

2024-01-03 22:24 UTC, samq-ws commented on Scripts/Mend SCA/get-library-ages.py
> +Optional Arguments: the only optional arguments for this script are WS_API_KEY and MEND_PRODUCT_TOKEN.
remove api_key and product_token and use uuids from API 2.0

2024-01-03 22:24 UTC, samq-ws commented on Scripts/Mend SCA/get-library-ages.py
> +python3 get-library-ages.py -o <output_file>.json -a <max_age_in_days>
uuids should be parameters

2024-01-03 22:24 UTC, samq-ws commented on Scripts/Mend SCA/get-library-ages.py
> +export MEND_PRODUCT_TOKEN='<PRODUCT_TOKEN>' <-- Optional
add a note on how to get productUUID from https://docs.mend.io/bundle/mend-api-2-0/page/index.html#tag/Entities-Organization/operation/getDomainEntities

2024-01-05 02:34 UTC, samq-ws approved these changes

2024-01-05 02:34 UTC, merged