Updated Azure Devops Pipelines
mend-toolkit/mend-examples pull request #188
Opened 2024-03-22 22:10 UTC by kyallanum-MND

Removes underscores from injected variables.

2024-03-22 22:31 UTC, samq-ws requested changes
Only the secrets need to have have underscores removed.  I would also add in a commented section about azure key vault
https://learn.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops&tabs=yaml

2024-03-25 04:43 UTC, kyallanum-MND commented
@samq-ws updated.

2024-03-25 04:45 UTC, kyallanum-MND commented
@samq-ws updated.

2024-03-26 02:06 UTC, samq-ws approved these changes

2024-03-26 02:06 UTC, merged