Add Gitlab advanced template
mend-toolkit/mend-examples pull request #219
Opened 2024-07-04 20:05 UTC by tabacmend

2024-07-05 17:55 UTC, lukebrogan-mend approved these changes

2024-07-07 14:43 UTC, samq-ws requested changes
the scan stage must be a part of the build stage since GitLab does not share artifacts.  This example is incorrect.  @tabacmend @lukebrogan-mend  , let's discuss offline. See lines 48-50 and the link in https://github.com/mend-toolkit/mend-examples/blob/main/CI-CD/GitLab/Mend%20CLI/gitlab-mend-cli-scan-template.yml

2024-07-07 19:21 UTC, samq-ws requested changes

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/README.md
> +By default, the template executes SCA, SAST and generate all reports which described above.
generates all reports which are described above.

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/README.md
> +If you wish to change it from the template or when you run the pipeline manually.
Not sure what this means.

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/README.md
> +In addition, all scan logs and reports are uploaded to each build stage.
Where are they uploaded?

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/.gitlab-ci.yaml
> +default:
this file is not necessary as the example should be provided in the README.md

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/.gitlab-ci.yaml
> +#   tags:
These tags are not available in Gitlab.com

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/.gitlab-ci.yaml
> +## NPM example - replace with your builds steps
move to bottom of readme as shown in https://gitlab.com/samqws-oritest/templates/-/blob/main/README.md

2024-07-07 19:21 UTC, samq-ws commented on CI-CD/GitLab/Mend CLI/Gitlab_template/.gitlab-ci.yaml
> +# maven_build:
uncomment and show in readme as shown in https://gitlab.com/samqws-oritest/templates/-/blob/main/README.md

2024-07-09 20:20 UTC, tabacmend commented
@samq-ws updated readme and removed the gitlab ci yaml.
pls review

2024-07-13 22:36 UTC, samq-ws approved these changes

2024-07-13 22:36 UTC, merged