Add Jenkins SCA Reachability
mend-toolkit/mend-examples pull request #237
Opened 2024-11-05 09:15 UTC by tabacmend

2024-11-05 20:22 UTC, Dima2021 commented
@tabacmend The code seems redundant in the MendSCAScan.groovy file. I recommend adding the "if" statement right before the "./mend dep" execution, as the rest of the code seems to be the same.
if (reachability) {
    ./mend dep -u -r -s "*//\${JOB_NAME}//\${repo}_\${branch}" --fail-policy --non-interactive --export-results dep-results.txt
 } else {
    ./mend dep -u -s "*//\${JOB_NAME}//\${repo}_\${branch}" --fail-policy --non-interactive --export-results dep-results.txt
}

2024-11-05 21:01 UTC, kyallanum-MND requested changes
Agree with Dima. These need to be changed before merging.

2024-11-05 21:01 UTC, kyallanum-MND commented on CI-CD/Jenkins/Mend CLI/vars/MendSCAScan.groovy
> +        if (reachability) {
This if statement should only be for the ``mend dep`` command. Everything else should only be in the script once.

2024-11-06 12:22 UTC, tabacmend commented
@kyallanum-MND @Dima2021 
See updated script.

2024-11-06 17:04 UTC, Dima2021 approved these changes

2024-11-06 21:12 UTC, kyallanum-MND approved these changes

2024-11-06 21:12 UTC, merged