Add Windows-Latest compatible YAML template for Java/Maven
mend-toolkit/mend-examples pull request #30
Opened 2022-12-14 11:58 UTC by Nick-Shamsfard-GIT

This is a template I created that will work on Windows-Latest agents in AZDO

2022-12-26 16:15 UTC, tabac-mend approved these changes

2022-12-26 16:20 UTC, tidharm requested changes
@Nick-Shamsfard-GIT for Maven scans, we should also add `WS_FILESYSTEMSCAN: false`

2023-01-09 11:32 UTC, tabac-mend commented on CI-CD/AzureDevOps/Azure-Pipelines_Windows_Maven
> +      WS_WSS_URL: https://saas-eu.mend.io/agent
change to saas.mend.io

2023-01-09 12:02 UTC, tidharm requested changes

2023-01-09 12:19 UTC, tidharm approved these changes

2023-01-09 12:19 UTC, merged