Refactor Mend CLI Folder
mend-toolkit/mend-examples pull request #80
Opened 2023-03-30 11:45 UTC by tabac-mend

Performed the following:
1. Structure Mend CLI folder similar to UA
2. Added Readme to Mend CLI
3. Removed Conan from UA/GH Readme
4. Updated name convention from WS to Mend in GH Actions for UA

2023-03-30 11:52 UTC, lukebrogan-mend requested changes

2023-03-30 11:52 UTC, lukebrogan-mend commented on Mend CLI/README.md
> +* [CodeFresh](CodeFresh)
Remove this

2023-03-30 13:01 UTC, lukebrogan-mend submitted a review, later dismissed

2023-04-06 11:23 UTC, lukebrogan-mend commented
A simpler unified CLI example can be found here, which we could use instead. Goal is to reduce number of files needed and complexity: https://github.com/lukebrogan-mend/Mend/blob/main/mend-azure-devops.yml

2023-04-06 13:00 UTC, samq-ws commented
> A simpler unified CLI example can be found here, which we could use instead. Goal is to reduce number of files needed and complexity: https://github.com/lukebrogan-mend/Mend/blob/main/mend-azure-devops.yml

Looks great, Luke.  My only suggestion would be to add another comment beneath the trigger recommending to scan on push to main and push to release branches since scanning release branches and the main branch are a best practice for pipeline scans.  Then we should do this per technology in this refactor instead of having so many files.

Example below, feel free to reword
```
# Define your own pipeline trigger here:
# Below is defined a trigger for scanning on a push to the main branch and scanning on a push to release branches.  This is considered an ideal time to scan so that an SBOM can be created for software releases and inventory is managed for released software.
trigger:
- main
- release*
```

2023-04-06 17:01 UTC, tabac-mend commented
The only downside with these examples is the need to "touch" the examples when having a call with a prospect. Therefore, created 4 examples per each use case. 

Let me know how to you want to proceed in order to update the PR.

2023-04-16 07:57 UTC, tabac-mend commented
Updated the structure except for Github.com as we have a README with plenty of good examples for the pre-steps.
How do you want to implement it? if we do it in one file, the example for GH will be very long.

2023-04-18 20:59 UTC, samq-ws commented
> Updated the structure except for Github.com as we have a README with plenty of good examples for the pre-steps. How do you want to implement it? if we do it in one file, the example for GH will be very long.

What README are you referring to?  The changes look really good so far.  Just trying to understand what you are referring to about GitHub.  In the future, please squash your commits before submitting a pull request as it is incredibly difficult to review right now.

2023-04-19 05:00 UTC, tabac-mend commented
> > Updated the structure except for Github.com as we have a README with plenty of good examples for the pre-steps. How do you want to implement it? if we do it in one file, the example for GH will be very long.
> 
> What README are you referring to? The changes look really good so far. Just trying to understand what you are referring to about GitHub. In the future, please squash your commits before submitting a pull request as it is incredibly difficult to review right now.

This is the README (from UA space): https://github.com/mend-toolkit/mend-examples/blob/main/Unified%20Agent/CI-CD/GitHub/README.md

2023-04-19 13:57 UTC, samq-ws commented
@tabac-mend , I'm going to merge this PR.  If you if you want to clean up the UA folder, please create a new PR.

2023-04-19 13:58 UTC, samq-ws approved these changes

2023-04-19 13:58 UTC, merged